USE submissions_db;

INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Frank Lloyd Wright', 'Gladys Wright House', 'Architecture', 'https://www.gannett-cdn.com/-mm-/1188b81b0dfcb3bdfcfab35a5aeba541b9b461a9/c=7-0-3393-1913/local/-/media/2015/05/01/Phoenix/Phoenix/635660948639481428-PNI-0425-Wright-House-Thursday-b.jpg?width=3200&height=1680&fit=crop', "The curving walls and ramp were a prelude to Wright's designs for the Guggenheim Museum", 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Zaha Hadid', 'Moscow Smart City', 'Architecture', 'https://static.dezeen.com/uploads/2018/11/rublyovo-arkhangelskoye-moscow-smart-city-zaha-hadid-architects-flying-architecture_dezeen_1704_hero_a-852x480.jpg', 'Moscow Smart City', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Renzo Piano', 'Paris Courthouse', 'Architecture', 'https://images.adsttc.com/media/images/5a14/5b63/b22e/385a/fe00/0006/slideshow/photo-sergio-grazia_IMP_2017-05-25_0740_TTT.jpg?1511283550', 'Paris Courthouse', 'NC');

INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Jeff Koons', 'Balloon Dog', 'Sculpture', 'https://mymodernmet.com/wp/wp-content/uploads/2017/08/famous-sculptures-jeff-koon-balloon-dog.jpg', 'Balloon Dog', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Louise Bourgeois', 'Maman', 'Sculpture', 'https://mymodernmet.com/wp/wp-content/uploads/2017/08/Famous-Sculptures-Louise-Bourgeois.jpg', 'Spider thing.', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Anish Kapoor', 'Cloud Gate', 'Sculpture', 'https://mymodernmet.com/wp/wp-content/uploads/2017/08/famous-sculptures-cloud-gate-anish-kapoor.jpg', 'Shiny', 'NC');

INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Yun Hee Lee', 'Untitled', 'Ceramics', 'https://d7hftxdivxxvm.cloudfront.net/?resize_to=width&src=https%3A%2F%2Fartsy-media-uploads.s3.amazonaws.com%2FRyGl-CNa-qv6uEu4Tzr-4A%252FAllegory-porcelain-220mm%2Bx%2B220mm%2Bx%2B270mm-2015%2B%25281%2529.jpg&width=1200&quality=80', 'Face thing', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Jami Porter Lara', 'Untitled', 'Ceramics', 'https://d7hftxdivxxvm.cloudfront.net/?resize_to=width&src=https%3A%2F%2Fartsy-media-uploads.s3.amazonaws.com%2FN09z18DzIKF9_3SJ-uCZRg%252FL161130002.jpg&width=1200&quality=80', 'Jugs', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Brian Rochefort', 'Untitled', 'Ceramics', 'https://d7hftxdivxxvm.cloudfront.net/?resize_to=width&src=https%3A%2F%2Fartsy-media-uploads.s3.amazonaws.com%2FWdrn09l8SL033ABTfMNknA%252FIMG_3301.JPG&width=1200&quality=80', 'Colorful', 'NC');

INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Jenny Saville', 'Reverse', 'Painting', 'https://d7hftxdivxxvm.cloudfront.net/?resize_to=width&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FVMTXhekDE_sKxd1Ve3X4eA%2Flarger.jpg&width=1200&quality=80', 'Drooling', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Vincent Van Gogh', 'The Starry Night', 'Painting', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fcdn-image.foodandwine.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fmedium_2x%2Fpublic%2Fkorean-latte-art-ftblog0717.jpg%3Fitok%3DJOMLIjL3&w=450&c=sc&poi=face&q=85', 'Swirly', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Leonardo da Vinci', 'The Mona Lisa', 'Painting', 'https://sep.yimg.com/ty/cdn/madisonartshop/most-famous-paintings-1.jpg?t=1544067607&', 'Mona Lisa', 'NC');

INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Stavros Damos', 'Famous', 'Illustration', 'http://www.graphicart-news.com/wp-content/uploads/2014/12/black-white-famous-by-stavros-damos-6.jpg', 'Black and white and famous', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Ben Brown', 'Frankenstein', 'Illustration', 'http://blog.downwit.com/wp-content/uploads/2010/08/bb3.jpg', 'Frankenstein', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Charles M. Schultz', 'Peanuts', 'Illustration', 'https://www.nyfa.edu/student-resources/wp-content/uploads/2015/04/beagle.jpg', 'Snoopy and friends', 'NC');

INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Erik Almas', 'Russian Dolls', 'Photography', 'http://webneel.com/daily/sites/default/files/images/daily/11-2017/15-russian-dolls-by-famous-photographer-erik-almas.preview.jpg', 'Russian Dolls', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Jimmy Nelson', 'Tribal', 'Photography', 'http://webneel.com/daily/sites/default/files/images/daily/11-2017/3-tribal-by-famous-photographer-jimmy-nelson.jpg', 'Tribal', 'NC');
INSERT INTO submissions (name, artTitle, category, photoURL, description, location) VALUES ('Lee Jeffries', 'Homeless', 'Photography', 'http://webneel.com/daily/sites/default/files/images/daily/11-2017/8-homeless-by-famous-photographer-lee-jeffries.jpg', 'Homeless', 'NC');